try {
    let num = 5;
    num.toUpperCase(); // Error!
} catch (error) {
    console.log("Error caught:", error.message);
}
